slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_topic: false
    mode: mapping  

    use_sim_time: true      
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    map_update_interval: 0.05  
    minimum_time_interval: 0.05  

    minimum_travel_distance: 0.01  
    minimum_travel_heading: 0.01  
    scan_queue_size: 1 
    use_scan_barycenter: true
    use_scan_matching: true
    max_laser_range: 3.5   
    resolution: 0.05

    loop_search_maximum_distance: 10.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_maximum_variance_fine: 0.05
    do_loop_closing: false  
    do_relocalization: false  
    use_scan_smoothing: false

